name: OpenSSF Scorecard Security Check

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  push:
    branches:
       - main
  pull_request:
    branches:
       - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  security-scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Scorecard Analysis
        uses: ossf/scorecard-action@v2.1.1
        with:
          results_file: results.sarif
          results_format: sarif

      - name: Upload Scorecard Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
